<body class="landing-page sidebar-collapse">
      <nav class="navbar navbar-color-on-scroll navbar-transparent    fixed-top  navbar-expand-lg " color-on-scroll="100"
         id="sectionsNav">
         <div class="container">
            <div class="navbar-translate">
               
               <span class="sr-only">Toggle navigation</span>
               <span class="navbar-toggler-icon"></span>
               <span class="navbar-toggler-icon"></span>
               <span class="navbar-toggler-icon"></span>
               </button>
            </div>
            <div class="collapse navbar-collapse">
               <ul class="navbar-nav ml-auto">
                  <li class="nav-item">
                     <a href="#" class="nav-link" data-toggle="dropdown">
                     <i class="material-icons">apps</i> Home
                     </a>
                  </li>
                  <li class="nav-item">
                     <a href="#" class="nav-link" data-toggle="dropdown">
                     <i class="material-icons">view_day</i> Contato
                     </a>
                  </li>
                  <li class="nav-item">
                     <a href="#" class="nav-link" data-toggle="dropdown">
                     <i class="material-icons">view_carousel</i> Área do usuário
                     </a>
                  </li>
                  <li class="button-container nav-item iframe-extern">
                     <a href="login" class="btn  btn-rose   btn-round btn-block">
                     <i class="material-icons">account_circle</i> Login
                     </a>
                  </li>
               </ul>
            </div>
         </div>
      </nav>
      <div class="page-header header-filter header-small" data-parallax="true" style="background-image: url('assets/img/technology.jpg')">
         <div class="container">
            <div class="row">
               <div class="col-md-6">
                  <h1 class="title">HelpDesk.</h1>
                  <h4>Nos somos Especializados em suporte de empresa e estamos que para te ajudar a resolver o seu problema.
                  </h4>
               </div>
            </div>
         </div>
      </div>
      <div class="main main-raised">
         <div class="container">
            <div class="section text-center">
               <div class="row">
                  <div class="col-md-8 ml-auto mr-auto">
                     <h2 class="title">Vamos falar de helpDesk</h2>
                     <h5 class="description">O serviço de help desk centraliza o recebimento das solicitações dos clientes, o que facilita as respostas e resolução dos problemas. Este serviço pode ser realizado tanto dentro de uma empresa, quanto externamente com a prestação de serviços aos usuários através de um sistema de call center ou gerenciamento de ocorrências.
                     </h5>
                  </div>
               </div>
               <div class="features">
                  <div class="row">
                     <div class="col-md-4">
                        <div class="info">
                           <div class="icon icon-info">
                              <i class="material-icons">schedule</i>
                           </div>
                           <h4 class="info-title">Menor tempo possivel</h4>
                           <p>Resolvemos o seu problema dentro de 24h ou menos, para que tenha um progresso rapido no trabalho.
                           </p>
                        </div>
                     </div>
                     <div class="col-md-4">
                        <div class="info">
                           <div class="icon icon-success">
                              <i class="material-icons">verified_user</i>
                           </div>
                           <h4 class="info-title">Garantia de segurança</h4>
                           <p>Suportes profissionais que garante o bom funcionamento e segurança da sua maquina, deixando sua empresa segura de quaalquer invasão ou problema 
                           </p>
                        </div>
                     </div>
                     <div class="col-md-4">
                        <div class="info">
                           <div class="icon icon-danger">
                              <i class="material-icons">visibility_off</i>
                           </div>
                           <h4 class="info-title">Dados Invisíveis</h4>
                           <p>Seus dados estarão sempre seguro em nosso sistema, Sera visivel apenas aquilo que interessa aos clientes.
                           </p>
                        </div>
                     </div>
                  </div>
               </div>
            </div>
            
            
         </div>
      </div>
      <footer class="footer footer-default">
         <div class="container">
            <nav class="float-left">
               <ul>
                  <li>
                     <a href="https://www.creative-tim.com">
                     OmniSmart
                     </a>
                  </li>
                  <li>
                     <a href="https://creative-tim.com/presentation">
                     About Us
                     </a>
                  </li>
                  <li>
                     <a href="http://blog.creative-tim.com">
                     Blog
                     </a>
                  </li>
                  <li>
                     <a href="https://www.creative-tim.com/license">
                     Licenses
                     </a>
                  </li>
               </ul>
            </nav>
            <div class="copyright float-right">
               &copy;
               <script>
                  document.write(new Date().getFullYear())
               </script>, made with <i class="material-icons">favorite</i> by
               <a href="http://helpdesk-pi.esy.es/home" target="_blank">OmniSmart</a> for a better web.
            </div>
         </div>
      </footer>