
<!DOCTYPE html>
<html lang="pt-BR">

<head>
    <meta charset="utf-8" />
    <link rel="apple-touch-icon" sizes="76x76" href="assets/img/icon.png">
    <!-- <link rel="icon" type="image/png" href="assets/img/icon.png"> -->
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />
    <title>
        <?= $title ?>
    </title>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no">
    <!--     Fonts and icons     -->
    <link rel="stylesheet" type="text/css" href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700|Roboto+Slab:400,700|Material+Icons" />
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/latest/css/font-awesome.min.css">
    <!-- Material Kit CSS -->
    <link href="assets/css/material-kit.css?v=2.1.0" rel="stylesheet" />
   
    <link href="assets/css/style.css?v=2.1.0" rel="stylesheet" />
    <link href="assets/css/custom.css?v=2.1.0" rel="stylesheet" />
    
    
    
    
    <link rel="stylesheet" type="text/css" href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700|Roboto+Slab:400,700|Material+Icons" />
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/latest/css/font-awesome.min.css">
  <!-- CSS Files -->
  <link href="assets/css/material-dashboard.css?v=2.1.0" rel="stylesheet" />
  <!-- CSS Just for demo purpose, don't include it in your project -->
  <link href="assets/demo/demo.css" rel="stylesheet" />
</head>

<body>
    <section>
        <!--  Todos os arquivos das views serão carregados aqui  -->
        <?php $this->controller->renderView(); ?>

    </section>

    <script type="text/javascript">
        $('.sidebar .sidebar-wrapper, .main-panel').perfectScrollbar();

        
        $('.main-panel').perfectScrollbar('destroy');

        
        $('.main-panel').perfectScrollbar('update');
    </script>

   <!--   Core JS Files   -->
      <script src="assets/js/core/jquery.min.js" type="text/javascript"></script>
      <script src="assets/js/core/popper.min.js" type="text/javascript"></script>
      <script src="assets/js/core/bootstrap-material-design.min.js" type="text/javascript"></script>
      <script src="assets/js/plugins/moment.min.js"></script>
      <!--	Plugin for the Datepicker, full documentation here: https://github.com/Eonasdan/bootstrap-datetimepicker -->
      <script src="assets/js/plugins/bootstrap-datetimepicker.js" type="text/javascript"></script>
      <!--  Plugin for the Sliders, full documentation here: http://refreshless.com/nouislider/ -->
      <script src="assets/js/plugins/nouislider.min.js" type="text/javascript"></script><!--  Google Maps Plugin  -->
      <script type="text/javascript" src="https://maps.googleapis.com/maps/api/js?key=AIzaSyB2Yno10-YTnLjjn_Vtk0V8cdcY5lC4plU"></script>
      <!--	Plugin for Tags, full documentation here: https://github.com/bootstrap-tagsinput/bootstrap-tagsinputs  -->
      <script src="assets/js/plugins/bootstrap-tagsinput.js"></script>
      <!--	Plugin for Select, full documentation here: http://silviomoreto.github.io/bootstrap-select -->
      <script src="assets/js/plugins/bootstrap-selectpicker.js" type="text/javascript"></script>
      <!--	Plugin for Fileupload, full documentation here: http://www.jasny.net/bootstrap/javascript/#fileinput -->
      <script src="assets/js/plugins/jasny-bootstrap.min.js" type="text/javascript"></script>
      <!--	Plugin for Small Gallery in Product Page -->
      <script src="assets/js/plugins/jquery.flexisel.js" type="text/javascript"></script>
      <!-- Plugins for presentation and navigation  -->
      <script src="assets/demo/modernizr.js" type="text/javascript"></script>
      <script src="assets/demo/vertical-nav.js" type="text/javascript"></script>
      <!-- Place this tag in your head or just before your close body tag. -->
      <script async defer src="https://buttons.github.io/buttons.js"></script>
      <!-- Js With initialisations For Demo Purpose, Don't Include it in Your Project -->
      <script src="assets/demo/demo.js" type="text/javascript"></script>
      <!-- Control Center for Material Kit: parallax effects, scripts for the example pages etc -->
      <script src="assets/js/material-kit.min.js?v=2.1.0" type="text/javascript"></script>
</body>

</html>